<?php
require_once __DIR__ . '/../wp-load.php';

echo "Populating authentic About page test settings..." . PHP_EOL;

$settings = array(
    'sections_order' => array(
        'hero'           => 10,
        'introduction'   => 20,
        'story'          => 30,
        'vision_mission' => 40,
        'values'         => 50,
        'quality'        => 60,
        'sourcing'       => 70,
        'manufacturing'  => 80,
        'statistics'     => 90,
        'milestones'     => 100,
        'leadership'     => 110,
        'certifications' => 120,
        'products'       => 130,
        'b2b_cta'        => 140,
        'final_cta'      => 150,
    ),
    'sections_enabled' => array(
        'hero'           => 1,
        'introduction'   => 1,
        'story'          => 1,
        'vision_mission' => 1,
        'values'         => 1,
        'quality'        => 1,
        'sourcing'       => 1,
        'manufacturing'  => 1,
        'statistics'     => 1,
        'milestones'     => 1,
        'leadership'     => 1,
        'certifications' => 1,
        'products'       => 1,
        'b2b_cta'        => 1,
        'final_cta'      => 1,
    ),
    'hero' => array(
        'eyebrow'             => 'Our Heritage & Craft',
        'heading'             => 'Pure Spices, Uncompromising Craftsmanship',
        'heading_highlight'   => 'Uncompromising Craftsmanship',
        'intro'               => 'From single-origin harvest fields to advanced cleanroom processing, SpiceCraft is dedicated to preserving the purest aroma, vibrant color, and therapeutic essential oils of authentic Indian spices.',
        'desktop_image_id'    => 31,
        'mobile_image_id'     => 31,
        'image_alt'           => 'Artisanal spices showcase featuring turmeric, cumin, and whole peppers',
        'cta_primary_label'   => 'Explore Our Spices',
        'cta_primary_url'     => '/shop/',
        'cta_secondary_label' => 'Our Sourcing Story',
        'cta_secondary_url'   => '#story',
    ),
    'introduction' => array(
        'eyebrow'            => 'About SpiceCraft',
        'heading'            => 'Rooted in Tradition, Elevated by Modern Precision',
        'content'            => '<p>SpiceCraft was founded with a singular conviction: that spices should never be compromised by adulteration, artificial fillers, or harsh processing.</p><p>We bridge traditional agricultural wisdom with modern cleanroom standards to deliver unadulterated excellence.</p>',
        'image_primary_id'   => 32,
        'image_secondary_id' => 33,
        'cta_label'          => 'Learn Our Process',
        'cta_url'            => '#manufacturing',
    ),
    'story' => array(
        'eyebrow'            => 'Our Journey',
        'heading'            => 'Born from a Passion for Unaltered Flavor',
        'content'            => '<p>Our journey began with a simple observation: modern commercial grinding strips away essential volatile oils through excessive friction heat.</p><p>We set out to change this paradigm by establishing low-temperature milling and micro-batch quality control.</p>',
        'image_id'           => 33,
        'image_secondary_id' => 31,
        'quote_text'         => 'A spice is not merely an ingredient; it is the living soul of culinary craft and natural wellness.',
        'quote_author'       => 'Founding Philosophy',
    ),
    'vision_mission' => array(
        'eyebrow'         => 'Purpose & Direction',
        'heading'         => 'Guided by Purpose, Driven by Quality',
        'description'     => 'Our core compass shapes how we partner with farmers and process every single grain.',
        'vision_enabled'  => 1,
        'vision_heading'  => 'Our Vision',
        'vision_content'  => 'To be globally recognized as the benchmark of spice purity, scientific integrity, and ethical agricultural partnerships.',
        'mission_enabled' => 1,
        'mission_heading' => 'Our Mission',
        'mission_content' => 'To supply clean, unadulterated, and aroma-rich spices by combining direct grower sourcing with state-of-the-art cleanroom manufacturing.',
    ),
    'values' => array(
        'eyebrow'     => 'Core Principles',
        'heading'     => 'The Values That Define SpiceCraft',
        'description' => 'Four foundational pillars govern every harvest we select and every packet we seal.',
        'items'       => array(
            array(
                'icon'        => 'shield-check',
                'title'       => 'Uncompromising Purity',
                'description' => 'Zero fillers, zero artificial colorants, and strict adherence to food safety standards.',
                'order'       => 10,
            ),
            array(
                'icon'        => 'leaf',
                'title'       => 'Ethical Sourcing',
                'description' => 'Direct partnerships with growers ensuring fair compensation and sustainable agriculture.',
                'order'       => 20,
            ),
            array(
                'icon'        => 'microscope',
                'title'       => 'Scientific Rigor',
                'description' => 'Laboratory testing of volatile oil content, moisture, and micro-biological purity on every batch.',
                'order'       => 30,
            ),
            array(
                'icon'        => 'award',
                'title'       => 'Culinary Authenticity',
                'description' => 'Preserving traditional aromatic flavor profiles designed for discerning palates and chefs.',
                'order'       => 40,
            ),
        ),
    ),
    'quality' => array(
        'eyebrow'     => 'Quality Standards',
        'heading'     => 'Precision Testing at Every Stage',
        'description' => 'Our quality framework integrates rigorous laboratory analytics from raw material receiving to finished packaging.',
        'image_id'    => 32,
        'points'      => array(
            'Multi-tier testing for moisture, ash content, and essential volatile oil retention.',
            'Cleanroom processing under positive air pressure to prevent cross-contamination.',
            'Stringent micro-biological screening compliant with international export norms.',
        ),
        'cta_label'   => 'Review Certifications',
        'cta_url'     => '#certifications',
    ),
    'sourcing' => array(
        'eyebrow'            => 'Origin & Harvest',
        'heading'            => 'Direct from Native Agro-Climatic Belts',
        'description'        => 'Spices thrive best in their native geography. We source turmeric from Salem, coriander from Rajasthan, and black pepper from the Malabar coast.',
        'image_id'           => 33,
        'image_secondary_id' => 31,
        'points'             => array(
            'Direct grower relationships that bypass multiple intermediary layers.',
            'Post-harvest sun-drying and sorting verification at regional collection points.',
            'Seasonal batch traceability from origin farm cluster to final packaged product.',
        ),
        'cta_label'          => 'Inquire on Origins',
        'cta_url'            => '#contact',
    ),
    'manufacturing' => array(
        'eyebrow'     => 'Production Standards',
        'heading'     => 'Low-Temperature Milling for Maximum Aroma',
        'description' => 'Conventional milling generates friction heat exceeding 60°C, evaporating volatile aromatic oils. Our low-temperature milling protects these delicate compounds.',
        'image_id'    => 32,
        'points'      => array(
            'Gentle low-temperature pulverizers preserving natural colors and volatile oils.',
            'Multi-stage magnetic separators and destoners eliminating physical foreign matter.',
            'High-barrier multi-layer packaging preventing moisture and photo-oxidation.',
        ),
        'cta_label'   => 'B2B Manufacturing Inquiry',
        'cta_url'     => '#b2b',
    ),
    'statistics' => array(
        'eyebrow'     => 'Key Metrics',
        'heading'     => 'SpiceCraft by the Numbers',
        'description' => 'Transparent benchmarks reflecting our standard of production.',
        'items'       => array(
            array(
                'value'       => '100',
                'suffix'      => '%',
                'label'       => 'Purity Tested',
                'description' => 'Every batch verified by lab analytics',
                'order'       => 10,
            ),
            array(
                'value'       => '4',
                'suffix'      => '+',
                'label'       => 'Signature Blends',
                'description' => 'Crafted for culinary excellence',
                'order'       => 20,
            ),
            array(
                'value'       => '0',
                'suffix'      => '',
                'label'       => 'Artificial Additives',
                'description' => 'Completely natural spices',
                'order'       => 30,
            ),
        ),
    ),
    'milestones' => array(
        'eyebrow'     => 'Timeline',
        'heading'     => 'The Milestones of Our Growth',
        'description' => 'From initial farm-gate partnerships to advanced certified manufacturing.',
        'items'       => array(
            array(
                'year'        => 'Phase 1',
                'title'       => 'Direct Sourcing Network',
                'description' => 'Established our direct agricultural sourcing network with spice cultivators across South India.',
                'image_id'    => 33,
                'order'       => 10,
            ),
            array(
                'year'        => 'Phase 2',
                'title'       => 'Cleanroom Facility',
                'description' => 'Commissioned our modern cleanroom processing facility with low-temperature grinding equipment.',
                'image_id'    => 32,
                'order'       => 20,
            ),
            array(
                'year'        => 'Phase 3',
                'title'       => 'Certification Benchmarks',
                'description' => 'Achieved organic handling accreditations and formal FSSAI licensing compliance.',
                'image_id'    => 0,
                'order'       => 30,
            ),
            array(
                'year'        => 'Phase 4',
                'title'       => 'B2B & Private Label',
                'description' => 'Inaugurated dedicated wholesale bulk and private label manufacturing operations for commercial clients.',
                'image_id'    => 31,
                'order'       => 40,
            ),
        ),
    ),
    'leadership' => array(
        'eyebrow'      => 'Leadership & People',
        'heading'      => 'Guided by Generational Passion and Food Science',
        'description'  => 'Meet the agronomists, master blenders, and quality directors behind SpiceCraft.',
        'limit'        => 4,
        'selected_ids' => array(),
    ),
    'certifications' => array(
        'eyebrow'      => 'Trust & Quality',
        'heading'      => 'Certified for Food Safety and Global Standards',
        'description'  => 'Our facilities adhere to stringent statutory licenses and organic standards.',
        'limit'        => 6,
        'selected_ids' => array(),
        'cta_label'    => 'View Product Catalog',
        'cta_url'      => '/shop/',
    ),
    'products' => array(
        'eyebrow'      => 'The Collection',
        'heading'      => 'Experience the SpiceCraft Distinction',
        'description'  => 'Browse our flagship single-origin spices and handcrafted spice blends.',
        'source'       => 'categories',
        'limit'        => 4,
        'selected_ids' => array(),
        'cta_label'    => 'Explore All Spices',
        'cta_url'      => '/shop/',
    ),
    'b2b_cta' => array(
        'eyebrow'             => 'B2B & Export Inquiries',
        'heading'             => 'Partner with a Modern Spice Manufacturer',
        'description'         => 'We provide certified bulk spice supply, custom recipe blending, and private label packaging for FMCG brands and international distributors.',
        'bg_image_id'         => 31,
        'primary_cta_label'   => 'Request B2B Quote',
        'primary_cta_url'     => '#contact',
        'secondary_cta_label' => 'Download Catalog',
        'secondary_cta_url'   => '/shop/',
        'show_whatsapp'       => 1,
    ),
    'final_cta' => array(
        'heading'       => 'Have Questions About Our Spices or Processing?',
        'description'   => 'Our quality directors and client partnership team are available to discuss bulk orders, custom blending, or retail supply.',
        'cta_label'     => 'Inquire Now',
        'cta_url'       => '#contact',
        'show_whatsapp' => 1,
        'show_email'    => 1,
    ),
);

// Save via SpiceCraft_About_Settings to execute full sanitization
$sanitized = SpiceCraft_About_Settings::get_instance()->sanitize_settings($settings);
update_option(SpiceCraft_About_Settings::OPTION_NAME, $sanitized);

echo "Settings saved successfully!" . PHP_EOL;
